### ISSUE TITLE
请问是否存在一些兼容问题，信息如图

### ISSUE THREAD

**Issue by sv3nbeast** [bigsizeme/fastjson-check#2]
![image](https://user-images.githubusercontent.com/55974091/142577945-c43b8ad2-6103-445f-bd53-d40e5526a254.png)
![image](https://user-images.githubusercontent.com/55974091/142578011-21fa7131-1fbc-431b-b586-623fe2cd8eea.png)

```
java.lang.NullPointerException
	at burp.fls.Z(Unknown Source)
	at burp.e6z.getHttpService(Unknown Source)
	at burp.hr9.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.h4t.a(Unknown Source)
	at burp.y0.a(Unknown Source)
	at burp.y0.a(Unknown Source)
	at burp.fyq.a(Unknown Source)
	at burp.g5c.b(Unknown Source)
	at burp.y0.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.yf.c(Unknown Source)
	at burp.yf.b(Unknown Source)
	at burp.yf.a(Unknown Source)
	at burp.yf.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.fls.Z(Unknown Source)
	at burp.e6z.getHttpService(Unknown Source)
	at burp.hr9.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.h4t.a(Unknown Source)
	at burp.y0.a(Unknown Source)
	at burp.y0.a(Unknown Source)
	at burp.fyq.a(Unknown Source)
	at burp.g5c.b(Unknown Source)
	at burp.y0.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.yf.c(Unknown Source)
	at burp.yf.b(Unknown Source)
	at burp.yf.a(Unknown Source)
	at burp.yf.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
DBCP_FASTJSON_TOMCATECHO-----------------------

```
感谢师傅提供的工具

**Comment by sv3nbeast** [comment]
没事，已解决
